site_name: Sabs' Mathematics Notes

nav:
  - Home: index.md
  - MAT102: mat102/index.md
  - CSC236: csc236/index.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: false